[build]
nixpacks = true

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "NEVER"

[build.nixPacks.phases.setup]
aptPkgs = ["ffmpeg"]

[build.nixPacks.phases.install]
dependsOn = ["setup"]

[build.nixPacks.phases.build]
dependsOn = ["install"]